//
//  FileCenter.swift
//  CodeNode
//
//  Created by xiong_jia on 2023/5/11.
//

import Foundation
import UniformTypeIdentifiers
import SwiftUI


/// 数据在文件中存储的格式
struct FileData: Codable {
    var text: String = ""
    var nodes: [Node] = []
}

/// 管理文件的存储
class FileCenter {
    
    let folderURL = FileManager.default.urls(for: .desktopDirectory, in: .userDomainMask).first?.appendingPathComponent("CodeNodeFolder")
    
    /// 在桌面中创建文件夹
    func createFolderOnDesktop() {
        do {
            try FileManager.default.createDirectory(at: self.folderURL!, withIntermediateDirectories: true)
        } catch {
            print("ERROR: create folder failed \(error.localizedDescription)")
        }
    }
    
    
    /// 保存文件
    func save(_ data: FileData, to file: String) throws {
        if file.count == 0 { return }
        
        let fileURL = folderURL?.appendingPathComponent(file)
        
        guard let fileURL = fileURL else { return }
        
        let encoder = JSONEncoder()
        let jsonData = try encoder.encode(data)
        
        try jsonData.write(to: fileURL)
    }

    
    /// read files in folder
    func readFiles() -> [String]? {
        do {
            let files = try FileManager.default.contentsOfDirectory(at: self.folderURL!, includingPropertiesForKeys: nil)
            
            // .DS_Store is a hidden file automatically generated by macOS.
            // It is used to store custom attributes and display settings for folders.
            // It is typically created during file operations on macOS.
            let fileNames = files
                                .filter { $0.lastPathComponent != ".DS_Store" }
                                .map { $0.lastPathComponent }
            
            return fileNames
        } catch {
            print("ERROR: read files failed --- \(error.localizedDescription)")
        }
        
        return nil
    }
    
    
    /// 读取指定路径的文件
    func readFile(_ file: String) throws -> FileData? {
        let fileURL = folderURL?.appendingPathComponent(file)
        
        guard let fileURL = fileURL else { return nil }
        
        let jsonData = try Data(contentsOf: fileURL)
        
        let decoder = JSONDecoder()
        return try decoder.decode(FileData.self, from: jsonData)
    }
    
    
    /// rename file with fileName
    /// file is the oldFileName
    func rename(_ file: String, with newfileName: String) throws {
        let oldFileURL = folderURL?.appendingPathComponent(file)
        let newFileURL = folderURL?.appendingPathComponent(newfileName)
        
        guard let oldFileURL = oldFileURL, let newFileURL = newFileURL else { return }
        
        try FileManager.default.moveItem(at: oldFileURL, to: newFileURL)
    }
}
